## Imports

In [1]:
import pandas as pd
import numpy as np
import nfl_data_py as nfl

## Data And Parameters

In [2]:
## modeling input paramters
K = 20  ##max elo change per game
HFA = 50  ##home field advantage
num_simulations = 10000
starting_seed = 1

In [3]:
## game level data
seasons = [2025]
schedule_df = nfl.import_schedules(years=seasons)
schedule_df = schedule_df[schedule_df['game_type']=='REG']
schedule_df=schedule_df[['week','away_team', 'home_team','result']]

In [4]:
## Remove already used weeks
schedule_df = schedule_df[schedule_df['week']!=1]
schedule_df = schedule_df[schedule_df['week']!=2]
schedule_df = schedule_df[schedule_df['week']!=3]
schedule_df = schedule_df[schedule_df['week']!=4]
schedule_df = schedule_df[schedule_df['week']!=5]
schedule_df = schedule_df[schedule_df['week']!=6]

In [5]:
## elo data
elo = pd.read_csv('elo_2025_week7.csv')  ## elo pulled from https://www.nfeloapp.com/nfl-power-ratings/
teams_df = elo.copy()
teams_df = teams_df[['Team', 'nfelo']]
#make team names consistent
teams_df['Team'] = teams_df['Team'].replace({'LAR': 'LA', 'OAK': 'LV'})

## Function Definitions

In [6]:
def simulate_full_season(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, seed=starting_seed):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        seed: for randomization

    Output:
        Dataframe: 1 row for each game throughout the entire season
            week. home_team, away_team, home_elo_before, away_elo_before, home_elo_after, away_elo_after, home_win_prob, away_win_prob, simulated_winner

    Methodology:
        Generates a record for each game.  Generates odds of each team winning, and simulates a winner based on those odds
        Updates ELO for both teams after the game, so they can be used in future games, allowing sull season to be simulated at a time
    """
    np.random.seed(seed)
    elo_ratings = teams_df.set_index('Team')['nfelo'].to_dict()
    all_game_results = []

    for week in sorted(schedule_df['week'].unique()):
        week_games = schedule_df[schedule_df['week'] == week]

        for df_index, df_game in week_games.iterrows():
            home_elo = elo_ratings[df_game['home_team']]
            away_elo = elo_ratings[df_game['away_team']]

            home_prob = 1/(1+10 **((away_elo-home_elo+HFA)/400))

            #simulate a winner
            winner = df_game['home_team'] if np.random.rand() < home_prob else df_game['away_team']

            if winner==df_game['home_team']:
                new_home_elo = home_elo + K * (1-home_prob)
                new_away_elo = away_elo + K * (home_prob-1)
            else:
                new_home_elo = home_elo + K * (0-home_prob)
                new_away_elo = away_elo + K * (home_prob-0)
            
            elo_ratings[df_game['home_team']] = new_home_elo
            elo_ratings[df_game['away_team']] = new_away_elo

            all_game_results.append({
                'week': week,
                'home_team': df_game['home_team'],
                'away_team': df_game['away_team'],
                'home_elo_before': home_elo,
                'away_elo_before': away_elo,
                'home_elo_after': new_home_elo,
                'away_elo_after': new_away_elo,
                'home_win_prob': home_prob,
                'away_win_prob': (1-home_prob),
                'simulated_winner': winner})
            
    return pd.DataFrame(all_game_results)

In [7]:
single_season_simulation = simulate_full_season(teams_df,schedule_df, 20, 50, 5)
single_season_simulation.head(5)

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,7,CIN,PIT,1397.69,1519.26,1412.262416,1504.687584,0.271379,0.728621,CIN
1,7,JAX,LA,1466.56,1614.31,1461.707496,1619.162504,0.242625,0.757375,LA
2,7,CHI,NO,1483.68,1358.40,1491.546550,1350.533450,0.606673,0.393327,CHI
3,7,CLE,MIA,1348.27,1426.49,1341.801577,1432.958423,0.323421,0.676579,MIA
4,7,KC,LV,1629.35,1398.40,1634.566705,1393.183295,0.739165,0.260835,KC

In [18]:
def global_survivor_path(simulated_season_df, win_metric='home_win_prob'):
    """
    Input:
        simulated_season_df: output of simulate_full_season
        win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home
    
    Output:
        list of teams in order of week selected.  None is first entry for week 0

    Methodology:
        Scans the season looking for the highest value of metric.
        Then that winning team is added to used_teams, and that week is dropped from data
        Then keep iterating through until a team is selected for each week

    """
    survivor_path = [None] * (19)
    used_teams = set()
    used_teams.update(['WAS', 'BAL', 'SEA', 'BUF', 'IND', 'GB'])
    remaining_games = simulated_season_df.copy()

    while remaining_games['week'].nunique()>0:
        if win_metric == 'home_win_prob':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_win_prob'] == iteration_df_1['home_win_prob'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df[iteration_df['away_win_prob'] == iteration_df['away_win_prob'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

        
        if win_metric == 'home_elo_difference':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[(iteration_df_1['home_elo_before']-iteration_df_1['away_elo_before']) == (iteration_df_1['home_elo_before'] - iteration_df_1['away_elo_before']).min()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
        
        if win_metric == 'home_elo_before':
            iteration_df = remaining_games.copy()
            iteration_df = iteration_df[~iteration_df['simulated_winner'].isin(used_teams)]
            iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['home_team']]
            if not iteration_df_1.empty:
                iteration_df_2 = iteration_df_1[iteration_df_1['home_elo_before'] == iteration_df_1['home_elo_before'].max()]
                win_team = iteration_df_2['home_team'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]
            else:
                iteration_df_1 = iteration_df[iteration_df['simulated_winner'] == iteration_df['away_team']]
                iteration_df_2 = iteration_df_1[iteration_df_1['away_elo_before'] == iteration_df_1['away_elo_before'].max()]
                win_team = iteration_df_2['away_win_prob'].iloc[0]
                win_week = iteration_df_2['week'].iloc[0]
                survivor_path[win_week] = iteration_df_2['simulated_winner'].iloc[0]
                used_teams.add(win_team)
                remaining_games = remaining_games[remaining_games['week']!=win_week]
                remaining_games = remaining_games[remaining_games['simulated_winner']!=win_team]

    return survivor_path

In [19]:
single_season_path = global_survivor_path(single_season_simulation, 'home_win_prob')
single_season_path

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 'KC',
 'PHI',
 'LA',
 'CHI',
 'ARI',
 'DET',
 'LAC',
 'CLE',
 'SF',
 'HOU',
 'LV',
 'ATL']

In [20]:
def simulate_full_season_multiple(teams_df=teams_df.copy(), schedule_df=schedule_df.copy(), K=K, HFA=HFA, simulations=num_simulations, seed = starting_seed, win_metric='home_win_prob'):
    """
    Input:
        teams_df: elo and team name
        schedule_df: week, home_team, away_team
        K: elo change per game
        HFA: home field advantage
        simulations: number of seasons you want to simulate
        seed: for randomization
            win_metric: what metric you want to use to calculate path
            home_win_prob: maximze win probability, emphasis on home
            home_elo_difference: maximize elo difference between teams, emphasis on home
            home_elo_before: maximize elo before game.  emphasis on home

    Output:
        List for each season simualted: contains all game results and best path
            Dictionary 'sim': get the number of the simulation
            Dictionary 'sim_games': get the game data for each simulated game.  Same output as simulate_full_season
            Dictionary 'sim_path': list of the teams selected by week.  Same output as global_survivor_path
    Methodology:
        Runs the simulate_full_season function and then finds the best path for that season global_survivor_path
        Increase the seed by 1, so each simulation is of a different season
    """
    all_season_results = []
    np.random.seed()

    for sim in range(simulations):
        sim_seed = seed+sim
        sim_games = simulate_full_season(teams_df.copy(), schedule_df.copy(), K, HFA, seed=sim_seed)
        sim_path = global_survivor_path(sim_games.copy(), win_metric=win_metric)

        all_season_results.append({
            'sim': sim+1,
            'sim_games': sim_games,
            'sim_path': sim_path})
    return all_season_results

In [21]:
many_season_simulation = simulate_full_season_multiple(teams_df, schedule_df, 20, 50, 100, 1, 'home_win_prob')

In [22]:
## example single season output
many_season_simulation[0]

{'sim': 1,
 'sim_games':      week home_team away_team  home_elo_before  away_elo_before  \
 0       7       CIN       PIT      1397.690000      1519.260000
 1       7       JAX        LA      1466.560000      1614.310000
 2       7       CHI        NO      1483.680000      1358.400000
 3       7       CLE       MIA      1348.270000      1426.490000
 4       7        KC        LV      1629.350000      1398.400000
 ..    ...       ...       ...              ...              ...
 174    18       NYG       DAL      1337.639439      1515.489343
 175    18       PHI       WAS      1522.095135      1527.388084
 176    18       PIT       BAL      1587.994846      1422.874745
 177    18        SF       SEA      1505.399018      1557.798541
 178    18        TB       CAR      1561.052569      1392.114665

      home_elo_after  away_elo_after  home_win_prob  away_win_prob  \
 0       1392.262416     1524.687584       0.271379       0.728621
 1       1461.707496     1619.162504       0.242625       0.757375
 2       1491.546550     1350.533450       0.606673       0.393327
 3       1361.801577     1412.958423       0.323421       0.676579
 4       1634.566705     1393.183295       0.739165       0.260835
 ..              ...             ...            ...            ...
 174     1333.395086     1519.733696       0.212218       0.787782
 175     1513.673293     1535.809926       0.421092       0.578908
 176     1574.797583     1436.072009       0.659863       0.340137
 177     1518.263838     1544.933721       0.356759       0.643241
 178     1567.757003     1385.410232       0.664778       0.335222

     simulated_winner
 0                PIT
 1                 LA
 2                CHI
 3                CLE
 4                 KC
 ..               ...
 174              DAL
 175              WAS
 176              BAL
 177               SF
 178               TB

 [179 rows x 10 columns],
 'sim_path': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  'KC',
  'PHI',
  'MIA',
  'DEN',
  'PIT',
  'DET',
  'LAC',
  'JAX',
  'SF',
  'HOU',
  'LV',
  'TB']}

In [23]:
## example of simulated season number
many_season_simulation[0]['sim']

1

In [24]:
## example of output of each game in simulated season
many_season_simulation[0]['sim_games']

,week,home_team,away_team,home_elo_before,away_elo_before,home_elo_after,away_elo_after,home_win_prob,away_win_prob,simulated_winner
0,7,CIN,PIT,1397.690000,1519.260000,1392.262416,1524.687584,0.271379,0.728621,PIT
1,7,JAX,LA,1466.560000,1614.310000,1461.707496,1619.162504,0.242625,0.757375,LA
2,7,CHI,NO,1483.680000,1358.400000,1491.546550,1350.533450,0.606673,0.393327,CHI
3,7,CLE,MIA,1348.270000,1426.490000,1361.801577,1412.958423,0.323421,0.676579,CLE
4,7,KC,LV,1629.350000,1398.400000,1634.566705,1393.183295,0.739165,0.260835,KC
...,...,...,...,...,...,...,...,...,...,...
174,18,NYG,DAL,1337.639439,1515.489343,1333.395086,1519.733696,0.212218,0.787782,DAL
175,18,PHI,WAS,1522.095135,1527.388084,1513.673293,1535.809926,0.421092,0.578908,WAS
176,18,PIT,BAL,1587.994846,1422.874745,1574.797583,1436.072009,0.659863,0.340137,BAL
177,18,SF,SEA,1505.399018,1557.798541,1518.263838,1544.933721,0.356759,0.643241,SF
178,18,TB,CAR,1561.052569,1392.114665,1567.757003,1385.410232,0.664778,0.335222,TB

In [25]:
## example of optimal survivor path for simulated season
many_season_simulation[0]['sim_path']

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 'KC',
 'PHI',
 'MIA',
 'DEN',
 'PIT',
 'DET',
 'LAC',
 'JAX',
 'SF',
 'HOU',
 'LV',
 'TB']

In [26]:
def pull_path_from_sim(seasons_list):
    """
    Inputs:
        seasons_list: output of simulate_full_season_multiple

    Outputs: 
        dataframe: simulation number as index, each week is a column
            so 1 row for each simulation with the team selected for that week ina  column

    Methodology:
        Extract the best paths data.
        Then create dataframe of simulations to make for easier analysis
    """
    all_paths = []
    for i in range(len(seasons_list)):
        sim_path = seasons_list[i]['sim_path']
        all_paths.append(sim_path)
    paths_df = pd.DataFrame(all_paths)
    paths_df.index = [f'sim_{i+1}' for i in range(len(all_paths))]
    paths_df.columns = [f'week_{i}' for i in range(paths_df.shape[1])]
    paths_df.drop('week_0', axis=1, inplace=True)

    return paths_df

In [27]:
many_season_simulation_paths = pull_path_from_sim(many_season_simulation)
many_season_simulation_paths

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,KC,PHI,MIA,DEN,PIT,DET,LAC,JAX,SF,HOU,LV,TB
sim_2,None,None,None,None,None,None,KC,PHI,LA,CHI,PIT,DET,CAR,TB,SF,NO,LV,JAX
sim_3,None,None,None,None,None,None,DEN,PHI,LA,NYJ,PIT,DET,LAC,JAX,CHI,HOU,KC,ATL
sim_4,None,None,None,None,None,None,KC,HOU,LA,CHI,PIT,DET,LAC,JAX,SF,DEN,NYJ,ATL
sim_5,None,None,None,None,None,None,KC,PHI,LA,CHI,ARI,DET,LAC,CLE,SF,HOU,LV,ATL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sim_96,None,None,None,None,None,None,KC,PHI,LA,DEN,ATL,DET,LAC,TB,SF,HOU,MIA,JAX
sim_97,None,None,None,None,None,None,DEN,PHI,LA,CHI,PIT,DET,NE,CLE,SF,NO,KC,JAX
sim_98,None,None,None,None,None,None,KC,NE,LA,DEN,PIT,DET,LAC,TB,SF,HOU,TEN,ATL
sim_99,None,None,None,None,None,None,NYJ,PHI,LA,DEN,NE,DET,LAC,KC,HOU,MIA,CIN,JAX
sim_100,None,None,None,None,None,None,KC,HOU,LA,DEN,NE,DET,MIA,TB,SF,MIN,TEN,CIN

## Running Simulations And Analysis

In [28]:
## week 1 picks over simulations
simulated_data_home_elo_before = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = starting_seed, win_metric='home_elo_before')
simulated_paths_home_elo_before = pull_path_from_sim(simulated_data_home_elo_before)
simulated_paths_home_elo_before.value_counts('week_7')

week_7
DEN    1690
KC     1669
CHI    1345
DAL    1095
DET     935
LAC     900
MIN     717
SF      444
NYJ     298
JAX     265
ARI     198
CIN     112
CLE     100
PIT      62
TEN      52
ATL      47
TB       20
NE       16
PHI      15
LA       10
MIA       5
HOU       5
Name: count, dtype: int64

In [29]:
## exmaple simulation
simulated_single_path_home_elo_before = simulated_paths_home_elo_before.iloc[[0]]
simulated_single_path_home_elo_before

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,CHI,PHI,MIA,DEN,MIN,SF,TB,LAC,PIT,DET,KC,LA

In [30]:
## week 1 picks over simulations
simulated_data_home_win_prob = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_win_prob')
simulated_paths_home_win_prob = pull_path_from_sim(simulated_data_home_win_prob)
simulated_paths_home_win_prob.value_counts('week_7')

week_7
KC     7323
DEN    1834
CHI     391
NYJ     155
DAL      53
LAC      50
SF       49
DET      30
CLE      27
MIN      23
CIN      15
NE       12
ARI      10
TEN       8
PIT       8
MIA       4
LA        4
JAX       2
ATL       1
PHI       1
Name: count, dtype: int64

In [31]:
## exmaple simulation
simulated_sinlge_path_home_win_prob = simulated_paths_home_win_prob.iloc[[0]]
simulated_sinlge_path_home_win_prob

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,KC,PHI,MIA,DEN,PIT,DET,LAC,JAX,SF,HOU,LV,TB

In [32]:
## week 1 picks over simulations
simulated_data_home_elo_difference = simulate_full_season_multiple(teams_df.copy(), schedule_df.copy(), K, HFA, simulations=10000, seed = 1, win_metric='home_elo_difference')
simulated_paths_home_elo_difference = pull_path_from_sim(simulated_data_home_elo_difference)
simulated_paths_home_elo_difference.value_counts('week_7')

week_7
KC     7323
DEN    1834
CHI     391
NYJ     155
DAL      53
LAC      50
SF       49
DET      30
CLE      27
MIN      23
CIN      15
NE       12
ARI      10
TEN       8
PIT       8
MIA       4
LA        4
JAX       2
ATL       1
PHI       1
Name: count, dtype: int64

In [33]:
## exmaple simulation
simulated_sinlge_path_home_elo_difference = simulated_paths_home_elo_difference.iloc[[0]]
simulated_sinlge_path_home_elo_difference

,week_1,week_2,week_3,week_4,week_5,week_6,week_7,week_8,week_9,week_10,week_11,week_12,week_13,week_14,week_15,week_16,week_17,week_18
sim_1,None,None,None,None,None,None,KC,PHI,MIA,DEN,PIT,DET,LAC,JAX,SF,HOU,LV,TB

In [34]:
simulated_paths_home_elo_difference.value_counts('week_8')

week_8
PHI    5318
NE     2647
CIN     417
ATL     344
HOU     267
LAC     221
DEN     133
NYJ     120
CHI     112
KC      103
PIT      84
NO       83
TB       62
CAR      54
MIN      22
MIA       8
DAL       3
CLE       1
SF        1
Name: count, dtype: int64

In [35]:
simulated_paths_home_elo_before.value_counts('week_8')

week_8
PHI    2250
KC     1709
HOU    1426
DEN    1089
ATL     849
NE      744
LAC     719
PIT     450
CIN     306
MIN      84
NO       82
TB       78
CAR      59
DAL      55
SF       32
MIA      27
CHI      26
NYJ      15
Name: count, dtype: int64

In [36]:
simulated_paths_home_win_prob.value_counts('week_8')

week_8
PHI    5318
NE     2647
CIN     417
ATL     344
HOU     267
LAC     221
DEN     133
NYJ     120
CHI     112
KC      103
PIT      84
NO       83
TB       62
CAR      54
MIN      22
MIA       8
DAL       3
CLE       1
SF        1
Name: count, dtype: int64

In [37]:
simulated_paths_home_elo_difference.value_counts('week_8')

week_8
PHI    5318
NE     2647
CIN     417
ATL     344
HOU     267
LAC     221
DEN     133
NYJ     120
CHI     112
KC      103
PIT      84
NO       83
TB       62
CAR      54
MIN      22
MIA       8
DAL       3
CLE       1
SF        1
Name: count, dtype: int64